services:

  nginx:
    image: mynginx_image
    container_name: web1
    ports:
      - "80:80"
    volumes:
      - nginxtest:/var/log/nginx
    networks:
      frontend:
        ipv4_address: 172.20.8.2



volumes:
  nginxtest:
    external: true

networks:
  frontend:
    external: true
